debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.board.projectboard: debug             #?? ??
    org.springframework.web.servlet: debug    #web.servlet? ??? ??
    org.hibernate.type.descriptor.sql.BasicBinder: trace  #jpa ?? ?? ??  ?? ???? ??

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/board
    username: gusdn
    password: thisisTEST!@#
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true     # 2.5?? data.sql?? ?? ?? ?? ??? ?? ??
    hibernate.ddl-auto: create                #entity ???? ddl ??
#    open-in-view: false
    show-sql: true                            # ?? ???
    properties:                               # ??? ???? ??
      hibernate.format_sql: true              # ??? ????? ???
      hibernate.default_batch_fetch_size: 100 #  (N+1)?? ?? ?? // ??? ?? select
  h2.console.enabled: false                   # H2 ? ??
  sql.init.mode: always                       # data.sql ?? ???
  # thymeleaf.cache: false

---
#??? db ?

#spring:
#  config.activate.on-profile: testdb
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driverClassName: org.h2.Driver
#  sql.init.mode: always
#  test.database.replace: none